import * as fs from 'fs';
import * as path from 'path';
import { runQueryAsync, getDatabaseName } from '../../repositories/util/ConnectionHandler';
import Logger from '../application/Logger';

const schemaOutputPath = path.join(__dirname, '..', '..', 'db', 'schema', 'schema.sql');

function toCreateIfNotExists(createTableStatement: string): string {
    return createTableStatement
        .replace(/^CREATE TABLE /, 'CREATE TABLE IF NOT EXISTS ')
        .replace(/ AUTO_INCREMENT=\d+/, '');
}

export async function dumpSchemaAsync(): Promise<void> {
    const databaseName = getDatabaseName();

    const tables = await runQueryAsync(`
        SELECT table_name AS TABLE_NAME
        FROM information_schema.tables
        WHERE table_schema = ?
        AND table_type = 'BASE TABLE'
        ORDER BY table_name
    `, [databaseName]) as Array<{ TABLE_NAME: string }>;

    const statements: string[] = [
        '-- Auto-generated by `npm run db:schema:dump`. Do not edit by hand.',
        '-- Regenerate whenever a table is created/altered in the live database.',
        'SET FOREIGN_KEY_CHECKS = 0;',
        '',
    ];

    for (const table of tables) {
        const tableName = table.TABLE_NAME;
        const rows = await runQueryAsync(`SHOW CREATE TABLE \`${tableName}\``) as Array<Record<string, string>>;
        const createStatement = rows?.[0]?.['Create Table'];
        if (!createStatement) {
            Logger.logWarning(`Skipping table '${tableName}': SHOW CREATE TABLE returned nothing`);
            continue;
        }
        statements.push(toCreateIfNotExists(createStatement) + ';', '');
    }

    statements.push('SET FOREIGN_KEY_CHECKS = 1;', '');

    fs.mkdirSync(path.dirname(schemaOutputPath), { recursive: true });
    fs.writeFileSync(schemaOutputPath, statements.join('\n'));
    Logger.logInfo(`Wrote schema for ${tables.length} table(s) to ${schemaOutputPath}`);
}
