import * as fs from 'fs';
import * as path from 'path';
import mysql from 'mysql2/promise';
import { runQueryAsync, getTableName } from '../../repositories/util/ConnectionHandler';
import { TableEnum } from '../../interfaces/enums/database/TableEnum';
import Logger from '../application/Logger';

const seedOutputPath = path.join(__dirname, '..', '..', 'db', 'schema', 'seed-data.sql');

// Order matters for seed tables
const SEED_TABLES = [TableEnum.DATASHEETS, TableEnum.GAME_DATA];
const GAME_DATA_ROWS_PER_GAME = 2;

function formatInsert(tableName: string, columns: string[], rows: Record<string, unknown>[]): string {
    const values = rows
        .map(row => `(${columns.map(col => mysql.escape(row[col])).join(', ')})`)
        .join(',\n  ');

    return `INSERT IGNORE INTO \`${tableName}\` (\`${columns.join('`, `')}\`) VALUES\n  ${values};`;
}

async function fetchSeedRows(tableEnum: TableEnum, tableName: string): Promise<Record<string, unknown>[]> {
    if (tableEnum === TableEnum.GAME_DATA) {
        return await runQueryAsync(`
            SELECT gd.* FROM (
                SELECT *, ROW_NUMBER() OVER (
                    PARTITION BY GameId ORDER BY (DataSheetId IS NULL) DESC, Id ASC
                ) AS rn
                FROM \`${tableName}\`
            ) AS gd
            WHERE gd.rn <= ?
        `, [GAME_DATA_ROWS_PER_GAME]) as Record<string, unknown>[];
    }

    return await runQueryAsync(`SELECT * FROM \`${tableName}\``) as Record<string, unknown>[];
}

export async function dumpSeedDataAsync(): Promise<void> {
    const statements: string[] = ['-- Auto-generated by `npm run db:down`. Do not edit by hand.', ''];

    for (const tableEnum of SEED_TABLES) {
        const tableName = getTableName(tableEnum);
        const rows = await fetchSeedRows(tableEnum, tableName);
        if (rows.length === 0)
            continue;

        const columns = Object.keys(rows[0]).filter(col => col !== 'rn');
        statements.push(formatInsert(tableName, columns, rows), '');
    }

    fs.mkdirSync(path.dirname(seedOutputPath), { recursive: true });
    fs.writeFileSync(seedOutputPath, statements.join('\n'));
    Logger.logInfo(`Wrote seed data for ${SEED_TABLES.length} table(s) to ${seedOutputPath}`);
}
