import * as fs from 'fs';
import * as path from 'path';
import mysql from 'mysql2/promise';
import { runQueryAsync, runExecuteAsync, getTableName } from '../../repositories/util/ConnectionHandler';
import { TableEnum } from '../../interfaces/enums/database/TableEnum';
import { StoredProcedureEnum } from '../../interfaces/enums/database/StoredProcedureEnum';
import Logger from '../application/Logger';

const seedOutputPath = path.join(__dirname, '..', '..', 'db', 'schema', 'seed-data.sql');

// Order matters for seed tables
const SEED_TABLES = [TableEnum.DATASHEETS, TableEnum.GAME_DATA];

// game_data holds the bot's real content (1300+ rows) — tests only need enough per
// GameId for GetRandomGameData to return something. The sampling itself (including the
// Connections-needs-4-rows special case) lives in GetGameDataSeedSample, alongside the
// other stored routines, rather than as raw SQL in this script.
const GAME_DATA_DEFAULT_ROWS_PER_GAME = 2;

function formatInsert(tableName: string, columns: string[], rows: Record<string, unknown>[]): string {
    const values = rows
        .map(row => `(${columns.map(col => mysql.escape(row[col])).join(', ')})`)
        .join(',\n  ');

    return `INSERT IGNORE INTO \`${tableName}\` (\`${columns.join('`, `')}\`) VALUES\n  ${values};`;
}

async function fetchSeedRows(tableEnum: TableEnum, tableName: string): Promise<Record<string, unknown>[]> {
    if (tableEnum === TableEnum.GAME_DATA) {
        const results = await runExecuteAsync(
            `CALL \`${StoredProcedureEnum.GetGameDataSeedSample}\`(?)`,
            [GAME_DATA_DEFAULT_ROWS_PER_GAME]
        );
        return (results?.[0] ?? []) as Record<string, unknown>[];
    }

    return await runQueryAsync(`SELECT * FROM \`${tableName}\``) as Record<string, unknown>[];
}

export async function dumpSeedDataAsync(): Promise<void> {
    const statements: string[] = ['-- Auto-generated by `npm run db:down`. Do not edit by hand.', ''];

    for (const tableEnum of SEED_TABLES) {
        const tableName = getTableName(tableEnum);
        const rows = await fetchSeedRows(tableEnum, tableName);
        if (rows.length === 0)
            continue;

        const columns = Object.keys(rows[0]);
        statements.push(formatInsert(tableName, columns, rows), '');
    }

    fs.mkdirSync(path.dirname(seedOutputPath), { recursive: true });
    fs.writeFileSync(seedOutputPath, statements.join('\n'));
    Logger.logInfo(`Wrote seed data for ${SEED_TABLES.length} table(s) to ${seedOutputPath}`);
}
