-- Auto-generated by `npm run db:schema:dump`. Do not edit by hand.
-- Regenerate whenever a table is created/altered in the live database.
SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE IF NOT EXISTS `datasheets` (
  `Id` int NOT NULL AUTO_INCREMENT,
  `ServerId` int DEFAULT NULL,
  `NameMLS` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `DescriptionMLS` text,
  PRIMARY KEY (`Id`),
  KEY `FK__servers` (`ServerId`),
  CONSTRAINT `FK__servers` FOREIGN KEY (`ServerId`) REFERENCES `servers` (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `debug` (
  `Id` int NOT NULL AUTO_INCREMENT,
  `UniqueCode` varchar(255) NOT NULL,
  `ServerId` int DEFAULT NULL,
  `DataJSON` text,
  `CreatedAt` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `UpdatedAt` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  KEY `fk_debug_server` (`ServerId`),
  CONSTRAINT `fk_debug_server` FOREIGN KEY (`ServerId`) REFERENCES `servers` (`Id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `events` (
  `Id` int unsigned NOT NULL AUTO_INCREMENT,
  `ServerId` int NOT NULL,
  `UserId` int DEFAULT NULL,
  `EventTypeEnum` int NOT NULL,
  `PayloadJSON` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `CreatedAt` timestamp NOT NULL,
  PRIMARY KEY (`Id`),
  KEY `events_ibfk_2` (`UserId`),
  KEY `events_ibfk_1` (`ServerId`),
  KEY `idx_events_cleanup` (`EventTypeEnum`,`CreatedAt`),
  CONSTRAINT `events_ibfk_1` FOREIGN KEY (`ServerId`) REFERENCES `servers` (`Id`) ON DELETE CASCADE,
  CONSTRAINT `events_ibfk_2` FOREIGN KEY (`UserId`) REFERENCES `users` (`Id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `game_data` (
  `Id` int NOT NULL AUTO_INCREMENT,
  `GameId` int NOT NULL,
  `DataSheetId` int DEFAULT NULL,
  `MessageMLS` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `ResponseMLS` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  PRIMARY KEY (`Id`) USING BTREE,
  UNIQUE KEY `uk_game_data_old_pk` (`GameId`,`ResponseMLS`(100)) USING BTREE,
  KEY `FK_game_data_datasheets` (`DataSheetId`),
  CONSTRAINT `FK_game_data_datasheets` FOREIGN KEY (`DataSheetId`) REFERENCES `datasheets` (`Id`),
  CONSTRAINT `game_data_ibfk_1` FOREIGN KEY (`GameId`) REFERENCES `game_type_enum` (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `game_type_enum` (
  `Id` int NOT NULL,
  `Name` varchar(255) NOT NULL,
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `games` (
  `Id` int NOT NULL AUTO_INCREMENT,
  `ChannelId` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `ServerId` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `GameTypeEnum` int NOT NULL DEFAULT '0',
  `Answer` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `LastUser` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `MessageId` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `SettingsJSON` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  PRIMARY KEY (`Id`) USING BTREE,
  UNIQUE KEY `uk_games_channelId` (`ChannelId`) USING BTREE,
  KEY `FK_games_servers` (`ServerId`) USING BTREE,
  KEY `FK_games_game_types` (`GameTypeEnum`) USING BTREE,
  KEY `ChannelId` (`ChannelId`),
  CONSTRAINT `FK_games_servers` FOREIGN KEY (`ServerId`) REFERENCES `servers` (`ServerId`) ON DELETE CASCADE,
  CONSTRAINT `games_ibfk_1` FOREIGN KEY (`GameTypeEnum`) REFERENCES `game_type_enum` (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `language_enum` (
  `Id` int NOT NULL,
  `Name` varchar(255) NOT NULL,
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `metrics` (
  `Id` int unsigned NOT NULL AUTO_INCREMENT,
  `MetricEnum` smallint NOT NULL,
  `Datetime` datetime NOT NULL,
  `Value` int NOT NULL,
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `points` (
  `Id` int NOT NULL AUTO_INCREMENT,
  `UserId` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `ServerId` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `GameId` int NOT NULL,
  `Points` int DEFAULT NULL,
  PRIMARY KEY (`Id`) USING BTREE,
  UNIQUE KEY `uk_points_old_pk` (`UserId`,`ServerId`,`GameId`) USING BTREE,
  KEY `FK_points_servers` (`ServerId`) USING BTREE,
  KEY `FK_points_game_types` (`GameId`) USING BTREE,
  CONSTRAINT `FK_points_servers` FOREIGN KEY (`ServerId`) REFERENCES `servers` (`ServerId`) ON DELETE CASCADE,
  CONSTRAINT `FK_user_users` FOREIGN KEY (`UserId`) REFERENCES `users` (`UserId`) ON DELETE CASCADE,
  CONSTRAINT `points_ibfk_1` FOREIGN KEY (`GameId`) REFERENCES `game_type_enum` (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `servers` (
  `Id` int NOT NULL AUTO_INCREMENT,
  `ServerId` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `Name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `LanguageEnum` int DEFAULT '1',
  `MemberCount` int DEFAULT '0',
  `IsPremium` tinyint DEFAULT '0',
  `SettingsJSON` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  PRIMARY KEY (`Id`) USING BTREE,
  UNIQUE KEY `uk_server_serverId` (`ServerId`) USING BTREE,
  KEY `ServerId` (`ServerId`),
  KEY `LanguageEnum` (`LanguageEnum`),
  CONSTRAINT `servers_ibfk_1` FOREIGN KEY (`LanguageEnum`) REFERENCES `language_enum` (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `statistics` (
  `Id` int NOT NULL AUTO_INCREMENT,
  `Date` date NOT NULL,
  `GameId` int NOT NULL,
  `Value` int DEFAULT NULL,
  PRIMARY KEY (`Id`) USING BTREE,
  UNIQUE KEY `uk_statistics_old_pk` (`Date`,`GameId`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `table_enum` (
  `Id` int NOT NULL,
  `Name` varchar(255) NOT NULL,
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `timeline_entries` (
  `Id` int NOT NULL AUTO_INCREMENT,
  `TableEnum` int NOT NULL,
  `ObjectId` int NOT NULL,
  `TimelineType` int NOT NULL,
  `UserId` int NOT NULL,
  `ServerId` int NOT NULL,
  `ChangesJSON` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `CreatedAt` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`Id`),
  KEY `idx_object` (`TableEnum`,`ObjectId`),
  KEY `idx_user` (`UserId`),
  KEY `idx_server` (`ServerId`),
  KEY `idx_type` (`TimelineType`),
  KEY `idx_created` (`CreatedAt`),
  CONSTRAINT `fk_timeline_server` FOREIGN KEY (`ServerId`) REFERENCES `servers` (`Id`) ON DELETE CASCADE,
  CONSTRAINT `fk_timeline_user` FOREIGN KEY (`UserId`) REFERENCES `users` (`Id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `users` (
  `Id` int NOT NULL AUTO_INCREMENT,
  `UserId` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `Username` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `UserRoleEnum` int NOT NULL DEFAULT '1',
  `ExperiencePoints` int NOT NULL DEFAULT '0',
  `StreakDays` int NOT NULL DEFAULT '0',
  `GamesPlayed` int NOT NULL DEFAULT '0',
  `CreatedAt` timestamp NULL DEFAULT NULL,
  `UpdatedAt` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`Id`) USING BTREE,
  UNIQUE KEY `Index 2` (`UserId`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `users_achievements` (
  `Id` int NOT NULL AUTO_INCREMENT,
  `UserId` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `AchievementEnum` tinyint NOT NULL,
  `Level` tinyint DEFAULT NULL,
  `CreatedAt` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

SET FOREIGN_KEY_CHECKS = 1;
