-- Auto-generated by `npm run db:down`. Do not edit by hand.

INSERT IGNORE INTO `datasheets` (`Id`, `ServerId`, `NameMLS`, `DescriptionMLS`) VALUES
  (1, NULL, '{\"1\": \"Christmas\", \"2\": \"Kerstmis\"}', '{\"1\": \"Christmas Description\", \"2\": \"Kerstmis Beschrijving\"}'),
  (2, NULL, '{\"1\": \"Halloween\", \"2\": \"Halloween\"}', '{\"1\": \"Halloween\", \"2\": \"Halloween bescrijving\"}'),
  (3, NULL, '{\"1\": \"Sports\", \"2\": \"Sporten\"}', '{\"1\": \"Sports Desc ({items} Items)\", \"2\": \"Sporten Beschrijving({items} Items)\"}');

INSERT IGNORE INTO `game_data` (`Id`, `GameId`, `DataSheetId`, `MessageMLS`, `ResponseMLS`) VALUES
  (1, 3, NULL, NULL, '{\"1\":\"adventure\",\"2\":\"avontuur\",\"3\":\"aventura\",\"4\":\"abenteuer\"}'),
  (16, 3, NULL, NULL, '{\"1\":\"airplane\",\"2\":\"vliegtuig\",\"3\":\"avion\",\"4\":\"flugzeug\"}'),
  (755, 4, NULL, NULL, '5124'),
  (1157, 5, NULL, '{ \"1\": \"What is the capital of France?\", \"2\": \"Wat is de hoofdstad van Frankrijk?\" }', '{ \"1\": \"paris\", \"2\": \"parijs\" }'),
  (1158, 5, NULL, '{ \"1\": \"What gas do humans breathe in?\", \"2\": \"Welk gas ademen mensen in?\" }', '{ \"1\": \"oxygen\", \"2\": \"zuurstof\" }'),
  (900, 8, NULL, NULL, '{\"1\":\"afghanistan\",\"2\":\"afghanistan\",\"3\":\"afghanistan\",\"4\":\"afghanistan\"}'),
  (901, 8, NULL, NULL, '{\"1\":\"albania\",\"2\":\"albanië\",\"3\":\"albanien\",\"4\":\"albanie\"}'),
  (1145, 9, NULL, '{\"1\": \"common components of board games\", \"2\": \"veelvoorkomende onderdelen van bordspellen\", \"3\": \"componentes comunes de los juegos de mesa\", \"4\": \"häufige Bestandteile von Brettspielen\"}', '{\"1\": \"board;cards;dice;pieces\", \"2\": \"bord;kaarten;dobbelstenen;pionnen\", \"3\": \"tablero;cartas;dados;fichas\", \"4\": \"spielbrett;karten;würfel;spielfiguren\"}'),
  (1146, 9, NULL, '{\"1\": \"primary colors\", \"2\": \"primaire kleuren\", \"3\": \"colores primarios\", \"4\": \"Grundfarben\"}', '{\"1\": \"red;blue;yellow;green\", \"2\": \"rood;blauw;geel;groen\", \"3\": \"rojo;azul;amarillo;verde\", \"4\": \"rot;blau;gelb;grün\"}'),
  (1147, 9, NULL, '{\"1\": \"planets in the solar system\", \"2\": \"planeten in het zonnestelsel\", \"3\": \"planetas del sistema solar\", \"4\": \"Planeten im Sonnensystem\"}', '{\"1\": \"mercury;venus;earth;mars\", \"2\": \"mercurius;venus;aarde;mars\", \"3\": \"mercurio;venus;tierra;marte\", \"4\": \"merkur;venus;erde;mars\"}'),
  (1148, 9, NULL, '{\"1\": \"popular programming languages\", \"2\": \"populaire programmeertalen\", \"3\": \"lenguajes de programación populares\", \"4\": \"beliebte Programmiersprachen\"}', '{\"1\": \"python;java;javascript;c#\", \"2\": \"python;java;javascript;c#\", \"3\": \"python;java;javascript;c#\", \"4\": \"python;java;javascript;c#\"}'),
  (3250, 10, NULL, '{\"1\":\"293358202496632\"}', '{\"1\":\"netherlands\"}'),
  (3251, 10, NULL, '{\"1\":\"120436613419795\"}', '{\"1\":\"germany\"}');
