-- Generated by db:down
CREATE PROCEDURE `GetGameDataSeedSample`(
	IN `p_DefaultLimit` INT
)
BEGIN
	/* Samples a handful of game_data rows per GameId for seeding a fresh/test database —
	   full production content stays in the real DB only. Connections (GameId 9) needs
	   4 rows per round (one per category), matching GetRandomGameData's own special case. */
	SELECT gd.Id, gd.GameId, gd.DataSheetId, gd.MessageMLS, gd.ResponseMLS FROM (
		SELECT *, ROW_NUMBER() OVER (
			PARTITION BY GameId ORDER BY (DataSheetId IS NULL) DESC, Id ASC
		) AS rn
		FROM game_data
	) AS gd
	WHERE gd.rn <= CASE gd.GameId WHEN 9 THEN 4 ELSE p_DefaultLimit END;
END
