-- Generated by db:down
CREATE PROCEDURE `LineChart_Discord_MemberUserGrowth`(
	IN `daysBack` INT
)
BEGIN
	SET SESSION TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

	WITH RECURSIVE day_seq AS (
		SELECT 0 AS n
		UNION ALL
		SELECT n + 1 FROM day_seq WHERE n < daysBack - 1
	),
	daily_totals AS (
		SELECT
			d.dayDate,
			DATE_FORMAT(d.dayDate, '%Y-%m-%d') AS dayStr,
			(
				SELECT m.Value
				FROM metrics m
				WHERE m.MetricEnum = 7
				  AND m.Datetime <= d.dayDate + INTERVAL 1 DAY - INTERVAL 1 SECOND
				ORDER BY m.Datetime DESC
				LIMIT 1
			) AS membersTotal,
			(
				SELECT m.Value
				FROM metrics m
				WHERE m.MetricEnum = 4
				  AND m.Datetime <= d.dayDate + INTERVAL 1 DAY - INTERVAL 1 SECOND
				ORDER BY m.Datetime DESC
				LIMIT 1
			) AS usersTotal
		FROM
		(
			SELECT DATE_SUB(CURDATE(), INTERVAL n DAY) AS dayDate
			FROM day_seq
		) d
	)
	SELECT JSON_OBJECT(
		'data',
		JSON_ARRAYAGG(
			JSON_OBJECT(
				'day', t.dayStr,
				'members', t.membersDelta,
				'users', t.usersDelta
			)
		),
		'xAxisKey', 'day',
		'valueKeys', JSON_ARRAY('members', 'users')
	) AS ChartDefinition
	FROM
	(
		SELECT
			dayStr,
			dayDate,
			membersTotal - LAG(membersTotal) OVER (ORDER BY dayDate) AS membersDelta,
			usersTotal - LAG(usersTotal) OVER (ORDER BY dayDate) AS usersDelta
		FROM daily_totals
		ORDER BY dayDate
	) t;

	SET SESSION TRANSACTION ISOLATION LEVEL REPEATABLE READ;
END
