-- Generated by db:down
CREATE PROCEDURE `LineChart_Discord_GuildServerGrowth`(
	IN `daysBack` INT
)
BEGIN
	SET SESSION TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

	WITH RECURSIVE day_seq AS (
		SELECT 0 AS n
		UNION ALL
		SELECT n + 1 FROM day_seq WHERE n < daysBack - 1
	),
	daily_totals AS (
		SELECT
			d.dayDate,
			DATE_FORMAT(d.dayDate, '%Y-%m-%d') AS dayStr,
			(
				SELECT m.Value
				FROM metrics m
				WHERE m.MetricEnum = 3
				  AND m.Datetime <= d.dayDate + INTERVAL 1 DAY - INTERVAL 1 SECOND
				ORDER BY m.Datetime DESC
				LIMIT 1
			) AS guildsTotal,
			(
				SELECT m.Value
				FROM metrics m
				WHERE m.MetricEnum = 2
				  AND m.Datetime <= d.dayDate + INTERVAL 1 DAY - INTERVAL 1 SECOND
				ORDER BY m.Datetime DESC
				LIMIT 1
			) AS serversTotal
		FROM
		(
			SELECT DATE_SUB(CURDATE(), INTERVAL n DAY) AS dayDate
			FROM day_seq
		) d
	)
	SELECT JSON_OBJECT(
		'data',
		JSON_ARRAYAGG(
			JSON_OBJECT(
				'day', t.dayStr,
				'guilds', t.guildsDelta,
				'servers', t.serversDelta
			)
		),
		'xAxisKey', 'day',
		'valueKeys', JSON_ARRAY('guilds', 'servers')
	) AS ChartDefinition
	FROM
	(
		SELECT
			dayStr,
			dayDate,
			guildsTotal - LAG(guildsTotal) OVER (ORDER BY dayDate) AS guildsDelta,
			serversTotal - LAG(serversTotal) OVER (ORDER BY dayDate) AS serversDelta
		FROM daily_totals
		ORDER BY dayDate
	) t;

	SET SESSION TRANSACTION ISOLATION LEVEL REPEATABLE READ;
END
