// This file is generated by generateDatabase.ts
import * as enums from "../../interfaces/enums";
import { MultiLingualString } from "../../utils/i18n/MultiLingualString";
import { Debug_Data, Events_Payload, Games_Settings, Servers_Settings, TimelineEntries_Changes } from "../domain";

import { BaseEntityClass } from '../../utils/database/BaseEntityClass';
import { BaseEntity, BaseEntityFieldType } from '../../interfaces/database/BaseEntity';

export interface DatasheetsModel {
  Id: number;
  ServerId: number;
  Name: MultiLingualString;
  Description: MultiLingualString;
}

export enum DatasheetsModelFieldEnum {
  Id = "Id",
  ServerId = "ServerId",
  Name = "Name",
  Description = "Description"
}

export function getDatasheetsFieldType(field: DatasheetsModelFieldEnum): BaseEntityFieldType {
  switch (field) {
    case DatasheetsModelFieldEnum.Id:
      return BaseEntityFieldType.Number;
    case DatasheetsModelFieldEnum.ServerId:
      return BaseEntityFieldType.Number;
    case DatasheetsModelFieldEnum.Name:
      return BaseEntityFieldType.MultiLingualString;
    case DatasheetsModelFieldEnum.Description:
      return BaseEntityFieldType.MultiLingualString;
  }
}

export class DatasheetsModel extends BaseEntityClass<DatasheetsModelFieldEnum> implements DatasheetsModel {
  protected static fieldEnum = DatasheetsModelFieldEnum;
  protected static tableEnum = enums.TableEnum.DATASHEETS;

  ServerId: number;
  Name: MultiLingualString;
  Description: MultiLingualString;

  constructor(data: Partial<DatasheetsModel>) {
    super(data as BaseEntity);
    this.Id = data.Id!;
    this.ServerId = data.ServerId!;
    this.Name = data.Name!;
    this.Description = data.Description!;
  }
}

export interface DatasheetsSaveModel {
  Id?: number;
  ServerId?: number;
  Name?: MultiLingualString;
  Description?: MultiLingualString;
}

export class DatasheetsSaveModel extends BaseEntityClass<DatasheetsModelFieldEnum> implements DatasheetsSaveModel {
  protected static fieldEnum = DatasheetsModelFieldEnum;
  protected static tableEnum = enums.TableEnum.DATASHEETS;

  ServerId?: number;
  Name?: MultiLingualString;
  Description?: MultiLingualString;

  constructor(data: Partial<DatasheetsSaveModel>) {
    super({ Id: data.Id ?? 0 });
    if (data.Id !== undefined) this.Id = data.Id;
    if (data.ServerId !== undefined) this.ServerId = data.ServerId;
    if (data.Name !== undefined) this.Name = data.Name;
    if (data.Description !== undefined) this.Description = data.Description;
  }
}

export interface DebugModel {
  Id: number;
  UniqueCode: string;
  ServerId: number;
  Data: Debug_Data;
  CreatedAt: Date;
  UpdatedAt: Date;
}

export enum DebugModelFieldEnum {
  Id = "Id",
  UniqueCode = "UniqueCode",
  ServerId = "ServerId",
  Data = "Data",
  CreatedAt = "CreatedAt",
  UpdatedAt = "UpdatedAt"
}

export function getDebugFieldType(field: DebugModelFieldEnum): BaseEntityFieldType {
  switch (field) {
    case DebugModelFieldEnum.Id:
      return BaseEntityFieldType.Number;
    case DebugModelFieldEnum.UniqueCode:
      return BaseEntityFieldType.String;
    case DebugModelFieldEnum.ServerId:
      return BaseEntityFieldType.Number;
    case DebugModelFieldEnum.Data:
      return BaseEntityFieldType.Json;
    case DebugModelFieldEnum.CreatedAt:
      return BaseEntityFieldType.Date;
    case DebugModelFieldEnum.UpdatedAt:
      return BaseEntityFieldType.Date;
  }
}

export class DebugModel extends BaseEntityClass<DebugModelFieldEnum> implements DebugModel {
  protected static fieldEnum = DebugModelFieldEnum;
  protected static tableEnum = enums.TableEnum.DEBUG;

  UniqueCode: string;
  ServerId: number;
  Data: Debug_Data;
  CreatedAt: Date;
  UpdatedAt: Date;

  constructor(data: Partial<DebugModel>) {
    super(data as BaseEntity);
    this.Id = data.Id!;
    this.UniqueCode = data.UniqueCode!;
    this.ServerId = data.ServerId!;
    this.Data = data.Data!;
    this.CreatedAt = data.CreatedAt!;
    this.UpdatedAt = data.UpdatedAt!;
  }
}

export interface DebugSaveModel {
  Id?: number;
  UniqueCode?: string;
  ServerId?: number;
  DataJSON?: Debug_Data;
  CreatedAt?: Date;
  UpdatedAt?: Date;
}

export class DebugSaveModel extends BaseEntityClass<DebugModelFieldEnum> implements DebugSaveModel {
  protected static fieldEnum = DebugModelFieldEnum;
  protected static tableEnum = enums.TableEnum.DEBUG;
  protected static fieldToPropertyMap: Record<string, string> = { Data: "DataJSON" };

  UniqueCode?: string;
  ServerId?: number;
  DataJSON?: Debug_Data;
  CreatedAt?: Date;
  UpdatedAt?: Date;

  constructor(data: Partial<DebugSaveModel>) {
    super({ Id: data.Id ?? 0 });
    if (data.Id !== undefined) this.Id = data.Id;
    if (data.UniqueCode !== undefined) this.UniqueCode = data.UniqueCode;
    if (data.ServerId !== undefined) this.ServerId = data.ServerId;
    if (data.DataJSON !== undefined) this.DataJSON = data.DataJSON;
    if (data.CreatedAt !== undefined) this.CreatedAt = data.CreatedAt;
    if (data.UpdatedAt !== undefined) this.UpdatedAt = data.UpdatedAt;
  }
}

export interface EventsModel {
  Id: number;
  ServerId: number;
  UserId: number;
  EventTypeEnum: enums.EventTypeEnum;
  Payload: Events_Payload;
  CreatedAt: Date;
}

export enum EventsModelFieldEnum {
  Id = "Id",
  ServerId = "ServerId",
  UserId = "UserId",
  EventTypeEnum = "EventTypeEnum",
  Payload = "Payload",
  CreatedAt = "CreatedAt"
}

export function getEventsFieldType(field: EventsModelFieldEnum): BaseEntityFieldType {
  switch (field) {
    case EventsModelFieldEnum.Id:
      return BaseEntityFieldType.Number;
    case EventsModelFieldEnum.ServerId:
      return BaseEntityFieldType.Number;
    case EventsModelFieldEnum.UserId:
      return BaseEntityFieldType.Number;
    case EventsModelFieldEnum.EventTypeEnum:
      return BaseEntityFieldType.Enum;
    case EventsModelFieldEnum.Payload:
      return BaseEntityFieldType.Json;
    case EventsModelFieldEnum.CreatedAt:
      return BaseEntityFieldType.Date;
  }
}

export class EventsModel extends BaseEntityClass<EventsModelFieldEnum> implements EventsModel {
  protected static fieldEnum = EventsModelFieldEnum;
  protected static tableEnum = enums.TableEnum.EVENTS;

  ServerId: number;
  UserId: number;
  EventTypeEnum: enums.EventTypeEnum;
  Payload: Events_Payload;
  CreatedAt: Date;

  constructor(data: Partial<EventsModel>) {
    super(data as BaseEntity);
    this.Id = data.Id!;
    this.ServerId = data.ServerId!;
    this.UserId = data.UserId!;
    this.EventTypeEnum = data.EventTypeEnum!;
    this.Payload = data.Payload!;
    this.CreatedAt = data.CreatedAt!;
  }
}

export interface EventsSaveModel {
  Id?: number;
  ServerId?: number;
  UserId?: number;
  EventTypeEnum?: enums.EventTypeEnum;
  PayloadJSON?: Events_Payload;
  CreatedAt?: Date;
}

export class EventsSaveModel extends BaseEntityClass<EventsModelFieldEnum> implements EventsSaveModel {
  protected static fieldEnum = EventsModelFieldEnum;
  protected static tableEnum = enums.TableEnum.EVENTS;
  protected static fieldToPropertyMap: Record<string, string> = { Payload: "PayloadJSON" };

  ServerId?: number;
  UserId?: number;
  EventTypeEnum?: enums.EventTypeEnum;
  PayloadJSON?: Events_Payload;
  CreatedAt?: Date;

  constructor(data: Partial<EventsSaveModel>) {
    super({ Id: data.Id ?? 0 });
    if (data.Id !== undefined) this.Id = data.Id;
    if (data.ServerId !== undefined) this.ServerId = data.ServerId;
    if (data.UserId !== undefined) this.UserId = data.UserId;
    if (data.EventTypeEnum !== undefined) this.EventTypeEnum = data.EventTypeEnum;
    if (data.PayloadJSON !== undefined) this.PayloadJSON = data.PayloadJSON;
    if (data.CreatedAt !== undefined) this.CreatedAt = data.CreatedAt;
  }
}

export interface GameDataModel {
  Id: number;
  GameId: number;
  DataSheetId: number;
  Message: MultiLingualString;
  Response: MultiLingualString;
}

export enum GameDataModelFieldEnum {
  Id = "Id",
  GameId = "GameId",
  DataSheetId = "DataSheetId",
  Message = "Message",
  Response = "Response"
}

export function getGameDataFieldType(field: GameDataModelFieldEnum): BaseEntityFieldType {
  switch (field) {
    case GameDataModelFieldEnum.Id:
      return BaseEntityFieldType.Number;
    case GameDataModelFieldEnum.GameId:
      return BaseEntityFieldType.Number;
    case GameDataModelFieldEnum.DataSheetId:
      return BaseEntityFieldType.Number;
    case GameDataModelFieldEnum.Message:
      return BaseEntityFieldType.MultiLingualString;
    case GameDataModelFieldEnum.Response:
      return BaseEntityFieldType.MultiLingualString;
  }
}

export class GameDataModel extends BaseEntityClass<GameDataModelFieldEnum> implements GameDataModel {
  protected static fieldEnum = GameDataModelFieldEnum;
  protected static tableEnum = enums.TableEnum.GAME_DATA;

  GameId: number;
  DataSheetId: number;
  Message: MultiLingualString;
  Response: MultiLingualString;

  constructor(data: Partial<GameDataModel>) {
    super(data as BaseEntity);
    this.Id = data.Id!;
    this.GameId = data.GameId!;
    this.DataSheetId = data.DataSheetId!;
    this.Message = data.Message!;
    this.Response = data.Response!;
  }
}

export interface GameDataSaveModel {
  Id?: number;
  GameId?: number;
  DataSheetId?: number;
  Message?: MultiLingualString;
  Response?: MultiLingualString;
}

export class GameDataSaveModel extends BaseEntityClass<GameDataModelFieldEnum> implements GameDataSaveModel {
  protected static fieldEnum = GameDataModelFieldEnum;
  protected static tableEnum = enums.TableEnum.GAME_DATA;

  GameId?: number;
  DataSheetId?: number;
  Message?: MultiLingualString;
  Response?: MultiLingualString;

  constructor(data: Partial<GameDataSaveModel>) {
    super({ Id: data.Id ?? 0 });
    if (data.Id !== undefined) this.Id = data.Id;
    if (data.GameId !== undefined) this.GameId = data.GameId;
    if (data.DataSheetId !== undefined) this.DataSheetId = data.DataSheetId;
    if (data.Message !== undefined) this.Message = data.Message;
    if (data.Response !== undefined) this.Response = data.Response;
  }
}

export interface GameTypeEnumModel {
  Id: number;
  Name: string;
}

export enum GameTypeEnumModelFieldEnum {
  Id = "Id",
  Name = "Name"
}

export function getGameTypeEnumFieldType(field: GameTypeEnumModelFieldEnum): BaseEntityFieldType {
  switch (field) {
    case GameTypeEnumModelFieldEnum.Id:
      return BaseEntityFieldType.Number;
    case GameTypeEnumModelFieldEnum.Name:
      return BaseEntityFieldType.String;
  }
}

export interface GamesModel {
  Id: number;
  ChannelId: string;
  ServerId: string;
  GameTypeEnum: enums.GameTypeEnum;
  Answer: string;
  LastUser: string;
  MessageId: string;
  Settings: Games_Settings;
}

export enum GamesModelFieldEnum {
  Id = "Id",
  ChannelId = "ChannelId",
  ServerId = "ServerId",
  GameTypeEnum = "GameTypeEnum",
  Answer = "Answer",
  LastUser = "LastUser",
  MessageId = "MessageId",
  Settings = "Settings"
}

export function getGamesFieldType(field: GamesModelFieldEnum): BaseEntityFieldType {
  switch (field) {
    case GamesModelFieldEnum.Id:
      return BaseEntityFieldType.Number;
    case GamesModelFieldEnum.ChannelId:
      return BaseEntityFieldType.String;
    case GamesModelFieldEnum.ServerId:
      return BaseEntityFieldType.String;
    case GamesModelFieldEnum.GameTypeEnum:
      return BaseEntityFieldType.Enum;
    case GamesModelFieldEnum.Answer:
      return BaseEntityFieldType.String;
    case GamesModelFieldEnum.LastUser:
      return BaseEntityFieldType.String;
    case GamesModelFieldEnum.MessageId:
      return BaseEntityFieldType.String;
    case GamesModelFieldEnum.Settings:
      return BaseEntityFieldType.Json;
  }
}

export class GamesModel extends BaseEntityClass<GamesModelFieldEnum> implements GamesModel {
  protected static fieldEnum = GamesModelFieldEnum;
  protected static tableEnum = enums.TableEnum.GAMES;

  ChannelId: string;
  ServerId: string;
  GameTypeEnum: enums.GameTypeEnum;
  Answer: string;
  LastUser: string;
  MessageId: string;
  Settings: Games_Settings;

  constructor(data: Partial<GamesModel>) {
    super(data as BaseEntity);
    this.Id = data.Id!;
    this.ChannelId = data.ChannelId!;
    this.ServerId = data.ServerId!;
    this.GameTypeEnum = data.GameTypeEnum!;
    this.Answer = data.Answer!;
    this.LastUser = data.LastUser!;
    this.MessageId = data.MessageId!;
    this.Settings = data.Settings!;
  }
}

export interface GamesSaveModel {
  Id?: number;
  ChannelId?: string;
  ServerId?: string;
  GameTypeEnum?: enums.GameTypeEnum;
  Answer?: string;
  LastUser?: string;
  MessageId?: string;
  SettingsJSON?: Games_Settings;
}

export class GamesSaveModel extends BaseEntityClass<GamesModelFieldEnum> implements GamesSaveModel {
  protected static fieldEnum = GamesModelFieldEnum;
  protected static tableEnum = enums.TableEnum.GAMES;
  protected static fieldToPropertyMap: Record<string, string> = { Settings: "SettingsJSON" };

  ChannelId?: string;
  ServerId?: string;
  GameTypeEnum?: enums.GameTypeEnum;
  Answer?: string;
  LastUser?: string;
  MessageId?: string;
  SettingsJSON?: Games_Settings;

  constructor(data: Partial<GamesSaveModel>) {
    super({ Id: data.Id ?? 0 });
    if (data.Id !== undefined) this.Id = data.Id;
    if (data.ChannelId !== undefined) this.ChannelId = data.ChannelId;
    if (data.ServerId !== undefined) this.ServerId = data.ServerId;
    if (data.GameTypeEnum !== undefined) this.GameTypeEnum = data.GameTypeEnum;
    if (data.Answer !== undefined) this.Answer = data.Answer;
    if (data.LastUser !== undefined) this.LastUser = data.LastUser;
    if (data.MessageId !== undefined) this.MessageId = data.MessageId;
    if (data.SettingsJSON !== undefined) this.SettingsJSON = data.SettingsJSON;
  }
}

export interface LanguageEnumModel {
  Id: number;
  Name: string;
}

export enum LanguageEnumModelFieldEnum {
  Id = "Id",
  Name = "Name"
}

export function getLanguageEnumFieldType(field: LanguageEnumModelFieldEnum): BaseEntityFieldType {
  switch (field) {
    case LanguageEnumModelFieldEnum.Id:
      return BaseEntityFieldType.Number;
    case LanguageEnumModelFieldEnum.Name:
      return BaseEntityFieldType.String;
  }
}

export interface MetricsModel {
  Id: number;
  MetricEnum: enums.MetricEnum;
  Datetime: Date;
  Value: number;
}

export enum MetricsModelFieldEnum {
  Id = "Id",
  MetricEnum = "MetricEnum",
  Datetime = "Datetime",
  Value = "Value"
}

export function getMetricsFieldType(field: MetricsModelFieldEnum): BaseEntityFieldType {
  switch (field) {
    case MetricsModelFieldEnum.Id:
      return BaseEntityFieldType.Number;
    case MetricsModelFieldEnum.MetricEnum:
      return BaseEntityFieldType.Enum;
    case MetricsModelFieldEnum.Datetime:
      return BaseEntityFieldType.Date;
    case MetricsModelFieldEnum.Value:
      return BaseEntityFieldType.Number;
  }
}

export class MetricsModel extends BaseEntityClass<MetricsModelFieldEnum> implements MetricsModel {
  protected static fieldEnum = MetricsModelFieldEnum;
  protected static tableEnum = enums.TableEnum.METRICS;

  MetricEnum: enums.MetricEnum;
  Datetime: Date;
  Value: number;

  constructor(data: Partial<MetricsModel>) {
    super(data as BaseEntity);
    this.Id = data.Id!;
    this.MetricEnum = data.MetricEnum!;
    this.Datetime = data.Datetime!;
    this.Value = data.Value!;
  }
}

export interface MetricsSaveModel {
  Id?: number;
  MetricEnum?: enums.MetricEnum;
  Datetime?: Date;
  Value?: number;
}

export class MetricsSaveModel extends BaseEntityClass<MetricsModelFieldEnum> implements MetricsSaveModel {
  protected static fieldEnum = MetricsModelFieldEnum;
  protected static tableEnum = enums.TableEnum.METRICS;

  MetricEnum?: enums.MetricEnum;
  Datetime?: Date;
  Value?: number;

  constructor(data: Partial<MetricsSaveModel>) {
    super({ Id: data.Id ?? 0 });
    if (data.Id !== undefined) this.Id = data.Id;
    if (data.MetricEnum !== undefined) this.MetricEnum = data.MetricEnum;
    if (data.Datetime !== undefined) this.Datetime = data.Datetime;
    if (data.Value !== undefined) this.Value = data.Value;
  }
}

export interface PointsModel {
  Id: number;
  UserId: string;
  ServerId: string;
  GameId: number;
  Points: number;
}

export enum PointsModelFieldEnum {
  Id = "Id",
  UserId = "UserId",
  ServerId = "ServerId",
  GameId = "GameId",
  Points = "Points"
}

export function getPointsFieldType(field: PointsModelFieldEnum): BaseEntityFieldType {
  switch (field) {
    case PointsModelFieldEnum.Id:
      return BaseEntityFieldType.Number;
    case PointsModelFieldEnum.UserId:
      return BaseEntityFieldType.String;
    case PointsModelFieldEnum.ServerId:
      return BaseEntityFieldType.String;
    case PointsModelFieldEnum.GameId:
      return BaseEntityFieldType.Number;
    case PointsModelFieldEnum.Points:
      return BaseEntityFieldType.Number;
  }
}

export class PointsModel extends BaseEntityClass<PointsModelFieldEnum> implements PointsModel {
  protected static fieldEnum = PointsModelFieldEnum;
  protected static tableEnum = enums.TableEnum.POINTS;

  UserId: string;
  ServerId: string;
  GameId: number;
  Points: number;

  constructor(data: Partial<PointsModel>) {
    super(data as BaseEntity);
    this.Id = data.Id!;
    this.UserId = data.UserId!;
    this.ServerId = data.ServerId!;
    this.GameId = data.GameId!;
    this.Points = data.Points!;
  }
}

export interface PointsSaveModel {
  Id?: number;
  UserId?: string;
  ServerId?: string;
  GameId?: number;
  Points?: number;
}

export class PointsSaveModel extends BaseEntityClass<PointsModelFieldEnum> implements PointsSaveModel {
  protected static fieldEnum = PointsModelFieldEnum;
  protected static tableEnum = enums.TableEnum.POINTS;

  UserId?: string;
  ServerId?: string;
  GameId?: number;
  Points?: number;

  constructor(data: Partial<PointsSaveModel>) {
    super({ Id: data.Id ?? 0 });
    if (data.Id !== undefined) this.Id = data.Id;
    if (data.UserId !== undefined) this.UserId = data.UserId;
    if (data.ServerId !== undefined) this.ServerId = data.ServerId;
    if (data.GameId !== undefined) this.GameId = data.GameId;
    if (data.Points !== undefined) this.Points = data.Points;
  }
}

export interface ServersModel {
  Id: number;
  ServerId: string;
  Name: string;
  LanguageEnum: enums.LanguageEnum;
  MemberCount: number;
  IsPremium: boolean;
  Settings: Servers_Settings;
}

export enum ServersModelFieldEnum {
  Id = "Id",
  ServerId = "ServerId",
  Name = "Name",
  LanguageEnum = "LanguageEnum",
  MemberCount = "MemberCount",
  IsPremium = "IsPremium",
  Settings = "Settings"
}

export function getServersFieldType(field: ServersModelFieldEnum): BaseEntityFieldType {
  switch (field) {
    case ServersModelFieldEnum.Id:
      return BaseEntityFieldType.Number;
    case ServersModelFieldEnum.ServerId:
      return BaseEntityFieldType.String;
    case ServersModelFieldEnum.Name:
      return BaseEntityFieldType.String;
    case ServersModelFieldEnum.LanguageEnum:
      return BaseEntityFieldType.Enum;
    case ServersModelFieldEnum.MemberCount:
      return BaseEntityFieldType.Number;
    case ServersModelFieldEnum.IsPremium:
      return BaseEntityFieldType.Boolean;
    case ServersModelFieldEnum.Settings:
      return BaseEntityFieldType.Json;
  }
}

export class ServersModel extends BaseEntityClass<ServersModelFieldEnum> implements ServersModel {
  protected static fieldEnum = ServersModelFieldEnum;
  protected static tableEnum = enums.TableEnum.SERVERS;

  ServerId: string;
  Name: string;
  LanguageEnum: enums.LanguageEnum;
  MemberCount: number;
  IsPremium: boolean;
  Settings: Servers_Settings;

  constructor(data: Partial<ServersModel>) {
    super(data as BaseEntity);
    this.Id = data.Id!;
    this.ServerId = data.ServerId!;
    this.Name = data.Name!;
    this.LanguageEnum = data.LanguageEnum!;
    this.MemberCount = data.MemberCount!;
    this.IsPremium = data.IsPremium!;
    this.Settings = data.Settings!;
  }
}

export interface ServersSaveModel {
  Id?: number;
  ServerId?: string;
  Name?: string;
  LanguageEnum?: enums.LanguageEnum;
  MemberCount?: number;
  IsPremium?: boolean;
  SettingsJSON?: Servers_Settings;
}

export class ServersSaveModel extends BaseEntityClass<ServersModelFieldEnum> implements ServersSaveModel {
  protected static fieldEnum = ServersModelFieldEnum;
  protected static tableEnum = enums.TableEnum.SERVERS;
  protected static fieldToPropertyMap: Record<string, string> = { Settings: "SettingsJSON" };

  ServerId?: string;
  Name?: string;
  LanguageEnum?: enums.LanguageEnum;
  MemberCount?: number;
  IsPremium?: boolean;
  SettingsJSON?: Servers_Settings;

  constructor(data: Partial<ServersSaveModel>) {
    super({ Id: data.Id ?? 0 });
    if (data.Id !== undefined) this.Id = data.Id;
    if (data.ServerId !== undefined) this.ServerId = data.ServerId;
    if (data.Name !== undefined) this.Name = data.Name;
    if (data.LanguageEnum !== undefined) this.LanguageEnum = data.LanguageEnum;
    if (data.MemberCount !== undefined) this.MemberCount = data.MemberCount;
    if (data.IsPremium !== undefined) this.IsPremium = data.IsPremium;
    if (data.SettingsJSON !== undefined) this.SettingsJSON = data.SettingsJSON;
  }
}

export interface StatisticsModel {
  Id: number;
  Date: Date;
  GameId: number;
  Value: number;
}

export enum StatisticsModelFieldEnum {
  Id = "Id",
  Date = "Date",
  GameId = "GameId",
  Value = "Value"
}

export function getStatisticsFieldType(field: StatisticsModelFieldEnum): BaseEntityFieldType {
  switch (field) {
    case StatisticsModelFieldEnum.Id:
      return BaseEntityFieldType.Number;
    case StatisticsModelFieldEnum.Date:
      return BaseEntityFieldType.Date;
    case StatisticsModelFieldEnum.GameId:
      return BaseEntityFieldType.Number;
    case StatisticsModelFieldEnum.Value:
      return BaseEntityFieldType.Number;
  }
}

export interface TableEnumModel {
  Id: number;
  Name: string;
}

export enum TableEnumModelFieldEnum {
  Id = "Id",
  Name = "Name"
}

export function getTableEnumFieldType(field: TableEnumModelFieldEnum): BaseEntityFieldType {
  switch (field) {
    case TableEnumModelFieldEnum.Id:
      return BaseEntityFieldType.Number;
    case TableEnumModelFieldEnum.Name:
      return BaseEntityFieldType.String;
  }
}

export interface TimelineEntriesModel {
  Id: number;
  TableEnum: enums.TableEnum;
  ObjectId: number;
  TimelineType: number;
  UserId: number;
  ServerId: number;
  Changes: TimelineEntries_Changes;
  CreatedAt: Date;
}

export enum TimelineEntriesModelFieldEnum {
  Id = "Id",
  TableEnum = "TableEnum",
  ObjectId = "ObjectId",
  TimelineType = "TimelineType",
  UserId = "UserId",
  ServerId = "ServerId",
  Changes = "Changes",
  CreatedAt = "CreatedAt"
}

export function getTimelineEntriesFieldType(field: TimelineEntriesModelFieldEnum): BaseEntityFieldType {
  switch (field) {
    case TimelineEntriesModelFieldEnum.Id:
      return BaseEntityFieldType.Number;
    case TimelineEntriesModelFieldEnum.TableEnum:
      return BaseEntityFieldType.Enum;
    case TimelineEntriesModelFieldEnum.ObjectId:
      return BaseEntityFieldType.Number;
    case TimelineEntriesModelFieldEnum.TimelineType:
      return BaseEntityFieldType.Number;
    case TimelineEntriesModelFieldEnum.UserId:
      return BaseEntityFieldType.Number;
    case TimelineEntriesModelFieldEnum.ServerId:
      return BaseEntityFieldType.Number;
    case TimelineEntriesModelFieldEnum.Changes:
      return BaseEntityFieldType.Json;
    case TimelineEntriesModelFieldEnum.CreatedAt:
      return BaseEntityFieldType.Date;
  }
}

export class TimelineEntriesModel extends BaseEntityClass<TimelineEntriesModelFieldEnum> implements TimelineEntriesModel {
  protected static fieldEnum = TimelineEntriesModelFieldEnum;
  protected static tableEnum = enums.TableEnum.TIMELINE_ENTRIES;

  TableEnum: enums.TableEnum;
  ObjectId: number;
  TimelineType: number;
  UserId: number;
  ServerId: number;
  Changes: TimelineEntries_Changes;
  CreatedAt: Date;

  constructor(data: Partial<TimelineEntriesModel>) {
    super(data as BaseEntity);
    this.Id = data.Id!;
    this.TableEnum = data.TableEnum!;
    this.ObjectId = data.ObjectId!;
    this.TimelineType = data.TimelineType!;
    this.UserId = data.UserId!;
    this.ServerId = data.ServerId!;
    this.Changes = data.Changes!;
    this.CreatedAt = data.CreatedAt!;
  }
}

export interface TimelineEntriesSaveModel {
  Id?: number;
  TableEnum?: enums.TableEnum;
  ObjectId?: number;
  TimelineType?: number;
  UserId?: number;
  ServerId?: number;
  ChangesJSON?: TimelineEntries_Changes;
  CreatedAt?: Date;
}

export class TimelineEntriesSaveModel extends BaseEntityClass<TimelineEntriesModelFieldEnum> implements TimelineEntriesSaveModel {
  protected static fieldEnum = TimelineEntriesModelFieldEnum;
  protected static tableEnum = enums.TableEnum.TIMELINE_ENTRIES;
  protected static fieldToPropertyMap: Record<string, string> = { Changes: "ChangesJSON" };

  TableEnum?: enums.TableEnum;
  ObjectId?: number;
  TimelineType?: number;
  UserId?: number;
  ServerId?: number;
  ChangesJSON?: TimelineEntries_Changes;
  CreatedAt?: Date;

  constructor(data: Partial<TimelineEntriesSaveModel>) {
    super({ Id: data.Id ?? 0 });
    if (data.Id !== undefined) this.Id = data.Id;
    if (data.TableEnum !== undefined) this.TableEnum = data.TableEnum;
    if (data.ObjectId !== undefined) this.ObjectId = data.ObjectId;
    if (data.TimelineType !== undefined) this.TimelineType = data.TimelineType;
    if (data.UserId !== undefined) this.UserId = data.UserId;
    if (data.ServerId !== undefined) this.ServerId = data.ServerId;
    if (data.ChangesJSON !== undefined) this.ChangesJSON = data.ChangesJSON;
    if (data.CreatedAt !== undefined) this.CreatedAt = data.CreatedAt;
  }
}

export interface UsersModel {
  Id: number;
  UserId: string;
  Username: string;
  UserRoleEnum: enums.UserRoleEnum;
  ExperiencePoints: number;
  StreakDays: number;
  GamesPlayed: number;
  CreatedAt: Date;
  UpdatedAt: Date;
}

export enum UsersModelFieldEnum {
  Id = "Id",
  UserId = "UserId",
  Username = "Username",
  UserRoleEnum = "UserRoleEnum",
  ExperiencePoints = "ExperiencePoints",
  StreakDays = "StreakDays",
  GamesPlayed = "GamesPlayed",
  CreatedAt = "CreatedAt",
  UpdatedAt = "UpdatedAt"
}

export function getUsersFieldType(field: UsersModelFieldEnum): BaseEntityFieldType {
  switch (field) {
    case UsersModelFieldEnum.Id:
      return BaseEntityFieldType.Number;
    case UsersModelFieldEnum.UserId:
      return BaseEntityFieldType.String;
    case UsersModelFieldEnum.Username:
      return BaseEntityFieldType.String;
    case UsersModelFieldEnum.UserRoleEnum:
      return BaseEntityFieldType.Enum;
    case UsersModelFieldEnum.ExperiencePoints:
      return BaseEntityFieldType.Number;
    case UsersModelFieldEnum.StreakDays:
      return BaseEntityFieldType.Number;
    case UsersModelFieldEnum.GamesPlayed:
      return BaseEntityFieldType.Number;
    case UsersModelFieldEnum.CreatedAt:
      return BaseEntityFieldType.Date;
    case UsersModelFieldEnum.UpdatedAt:
      return BaseEntityFieldType.Date;
  }
}

export class UsersModel extends BaseEntityClass<UsersModelFieldEnum> implements UsersModel {
  protected static fieldEnum = UsersModelFieldEnum;
  protected static tableEnum = enums.TableEnum.USERS;

  UserId: string;
  Username: string;
  UserRoleEnum: enums.UserRoleEnum;
  ExperiencePoints: number;
  StreakDays: number;
  GamesPlayed: number;
  CreatedAt: Date;
  UpdatedAt: Date;

  constructor(data: Partial<UsersModel>) {
    super(data as BaseEntity);
    this.Id = data.Id!;
    this.UserId = data.UserId!;
    this.Username = data.Username!;
    this.UserRoleEnum = data.UserRoleEnum!;
    this.ExperiencePoints = data.ExperiencePoints!;
    this.StreakDays = data.StreakDays!;
    this.GamesPlayed = data.GamesPlayed!;
    this.CreatedAt = data.CreatedAt!;
    this.UpdatedAt = data.UpdatedAt!;
  }
}

export interface UsersSaveModel {
  Id?: number;
  UserId?: string;
  Username?: string;
  UserRoleEnum?: enums.UserRoleEnum;
  ExperiencePoints?: number;
  StreakDays?: number;
  GamesPlayed?: number;
  CreatedAt?: Date;
  UpdatedAt?: Date;
}

export class UsersSaveModel extends BaseEntityClass<UsersModelFieldEnum> implements UsersSaveModel {
  protected static fieldEnum = UsersModelFieldEnum;
  protected static tableEnum = enums.TableEnum.USERS;

  UserId?: string;
  Username?: string;
  UserRoleEnum?: enums.UserRoleEnum;
  ExperiencePoints?: number;
  StreakDays?: number;
  GamesPlayed?: number;
  CreatedAt?: Date;
  UpdatedAt?: Date;

  constructor(data: Partial<UsersSaveModel>) {
    super({ Id: data.Id ?? 0 });
    if (data.Id !== undefined) this.Id = data.Id;
    if (data.UserId !== undefined) this.UserId = data.UserId;
    if (data.Username !== undefined) this.Username = data.Username;
    if (data.UserRoleEnum !== undefined) this.UserRoleEnum = data.UserRoleEnum;
    if (data.ExperiencePoints !== undefined) this.ExperiencePoints = data.ExperiencePoints;
    if (data.StreakDays !== undefined) this.StreakDays = data.StreakDays;
    if (data.GamesPlayed !== undefined) this.GamesPlayed = data.GamesPlayed;
    if (data.CreatedAt !== undefined) this.CreatedAt = data.CreatedAt;
    if (data.UpdatedAt !== undefined) this.UpdatedAt = data.UpdatedAt;
  }
}

export interface UsersAchievementsModel {
  Id: number;
  UserId: string;
  AchievementEnum: number;
  Level: number;
  CreatedAt: Date;
}

export enum UsersAchievementsModelFieldEnum {
  Id = "Id",
  UserId = "UserId",
  AchievementEnum = "AchievementEnum",
  Level = "Level",
  CreatedAt = "CreatedAt"
}

export function getUsersAchievementsFieldType(field: UsersAchievementsModelFieldEnum): BaseEntityFieldType {
  switch (field) {
    case UsersAchievementsModelFieldEnum.Id:
      return BaseEntityFieldType.Number;
    case UsersAchievementsModelFieldEnum.UserId:
      return BaseEntityFieldType.String;
    case UsersAchievementsModelFieldEnum.AchievementEnum:
      return BaseEntityFieldType.Number;
    case UsersAchievementsModelFieldEnum.Level:
      return BaseEntityFieldType.Number;
    case UsersAchievementsModelFieldEnum.CreatedAt:
      return BaseEntityFieldType.Date;
  }
}

export class UsersAchievementsModel extends BaseEntityClass<UsersAchievementsModelFieldEnum> implements UsersAchievementsModel {
  protected static fieldEnum = UsersAchievementsModelFieldEnum;
  protected static tableEnum = enums.TableEnum.USERS_ACHIEVEMENTS;

  UserId: string;
  AchievementEnum: number;
  Level: number;
  CreatedAt: Date;

  constructor(data: Partial<UsersAchievementsModel>) {
    super(data as BaseEntity);
    this.Id = data.Id!;
    this.UserId = data.UserId!;
    this.AchievementEnum = data.AchievementEnum!;
    this.Level = data.Level!;
    this.CreatedAt = data.CreatedAt!;
  }
}

export interface UsersAchievementsSaveModel {
  Id?: number;
  UserId?: string;
  AchievementEnum?: number;
  Level?: number;
  CreatedAt?: Date;
}

export class UsersAchievementsSaveModel extends BaseEntityClass<UsersAchievementsModelFieldEnum> implements UsersAchievementsSaveModel {
  protected static fieldEnum = UsersAchievementsModelFieldEnum;
  protected static tableEnum = enums.TableEnum.USERS_ACHIEVEMENTS;

  UserId?: string;
  AchievementEnum?: number;
  Level?: number;
  CreatedAt?: Date;

  constructor(data: Partial<UsersAchievementsSaveModel>) {
    super({ Id: data.Id ?? 0 });
    if (data.Id !== undefined) this.Id = data.Id;
    if (data.UserId !== undefined) this.UserId = data.UserId;
    if (data.AchievementEnum !== undefined) this.AchievementEnum = data.AchievementEnum;
    if (data.Level !== undefined) this.Level = data.Level;
    if (data.CreatedAt !== undefined) this.CreatedAt = data.CreatedAt;
  }
}

