export enum MetricEnum {
    ActiveGames = 1,
    Servers = 2,
    Guilds = 3,
    Users = 4,
    Points = 5,
    Events = 6,
    Members = 7,
    ServerMembers = 8,
    AdoptionRate = 9,
    InactivityRate = 10,
    GamesPlayed = 11,
    GamesEnded = 12,
    CommandsUsed = 13,
    PremiumConversions = 14,
    PremiumChurn = 15,
    ErrorRate = 16,
}